image:
    gcc

stages:
    - build
    - test

before_script:
    - apt-get update --yes
    - apt-get install git --yes
    - apt-get install cmake --yes
    - apt-get install lcov --yes

build:
    stage: build
    script:
        - cd assignment/build
        - cmake ..
        - make

tdd:
    stage: test
    script:
        - ./tdd_test
