image:
    gcc

stages:
    - build
    - test

build:
    stage: build
    script:
        - apt-get update --yes
        - apt-get install git --yes
        - apt-get install cmake --yes
        - apt-get install lcov --yes
        - cd assignment/build
        - cmake ..
        - make

tdd:
    stage: test
    script:
        - cd assignment/build
        - cmake ..
        - make
        - ./tdd_test
